### PR TITLE
Add many-to-many, no structural integration

### PR DESCRIPTION
**Pull request by IanLockwood**

### CODE REVIEW

**Comment by IanLockwood** [comment]
@linkblaine @cdimartino

**Review by cdimartino — COMMENTED** [review]
close this pr already :)

**Comment by IanLockwood** [comment]
Ahaha maybe I should leave it open forever, for old times' sake?

**Comment by cdimartino** [comment]
CLOSE IT!!!!  How's it going Ian?

**Comment by cdimartino** [comment]
I can't get it out of my "mentioned" pr's otherwise :/

**Comment by IanLockwood** [comment]
Closed! Sorry about that - I can definitely respect wanting to clear up your github to perfection :)

I'm doing great! Hope things are going well with you too.

**Pull request closed without merging**
